"""ADR 0008: the artifact's value domain and serialisation are closed and pinned.

The dedicated serialisation family -- emission, round-trip, rejection --
is the one place bytes are compared rather than parsed values.
"""

from __future__ import annotations

import json

import yaml

from tests.conftest import assert_diagnostic, run_reverie


def test_emission_mechanics_are_pinned(fixture_dir):
    source = fixture_dir("minimal")
    run_reverie("compile", str(source))

    raw = (source / "host_vars" / "host1.yml").read_bytes()

    assert not raw.startswith(b"\xef\xbb\xbf")  # no BOM
    assert b"\r\n" not in raw
    text = raw.decode("utf-8")
    assert text.startswith("# Generated by Reverie")
    assert "\n---\n" in text
    assert "reverie:" in text
    assert "  site: dublin" in text  # two-space indent, block style


def test_emission_map_keys_sorted_at_every_depth(fixture_dir):
    source = fixture_dir("minimal")
    run_reverie("compile", str(source))

    text = (source / "host_vars" / "host1.yml").read_text(encoding="utf-8")
    lines = [line for line in text.splitlines() if line and not line.startswith("#") and line != "---"]

    # reverie: sorts before reverie_meta: at the top level.
    top_level = [line for line in lines if not line.startswith(" ")]
    assert top_level == sorted(top_level)


def test_round_trip_under_plain_yaml11_loader(fixture_dir):
    source = fixture_dir("minimal")
    run_reverie("compile", str(source))

    text = (source / "host_vars" / "host1.yml").read_text(encoding="utf-8")
    loaded = yaml.load(text, Loader=yaml.SafeLoader)

    assert loaded["reverie"] == {"site": "dublin"}
    assert type(loaded["reverie"]["site"]) is str


def test_binary_value_is_rejected(fixture_dir):
    source = fixture_dir("minimal")
    (source / "defaults" / "common.yml").write_text(
        "site: dublin\nblob: !!binary |\n  aGVsbG8=\n", encoding="utf-8"
    )

    result = run_reverie("compile", str(source))

    assert result.returncode != 0
    diagnostics = json.loads(result.stderr)
    assert_diagnostic(diagnostics, "load.value_out_of_domain", kind="binary")


def test_set_value_is_rejected(fixture_dir):
    source = fixture_dir("minimal")
    (source / "defaults" / "common.yml").write_text(
        "site: dublin\ntags: !!set\n  ? a\n  ? b\n", encoding="utf-8"
    )

    result = run_reverie("compile", str(source))

    assert result.returncode != 0
    diagnostics = json.loads(result.stderr)
    assert_diagnostic(diagnostics, "load.value_out_of_domain", kind="set")


def test_anchors_and_aliases_are_rejected(fixture_dir):
    source = fixture_dir("minimal")
    (source / "defaults" / "common.yml").write_text(
        "base: &base dublin\nsite: *base\n", encoding="utf-8"
    )

    result = run_reverie("compile", str(source))

    assert result.returncode != 0
    diagnostics = json.loads(result.stderr)
    assert_diagnostic(diagnostics, "load.value_out_of_domain", kind="anchor_or_alias")


def test_merge_key_via_alias_is_rejected(fixture_dir):
    source = fixture_dir("minimal")
    (source / "defaults" / "common.yml").write_text(
        "base: &base\n  site: dublin\nsite:\n  <<: *base\n", encoding="utf-8"
    )

    result = run_reverie("compile", str(source))

    assert result.returncode != 0
    diagnostics = json.loads(result.stderr)
    # The alias (`*base`) is itself forbidden, ahead of the merge key check.
    assert_diagnostic(diagnostics, "load.value_out_of_domain", kind="anchor_or_alias")


def test_merge_key_via_literal_mapping_is_rejected(fixture_dir):
    # No anchor or alias involved -- exercises the dedicated merge-key
    # check (flatten_mapping), not the anchor/alias check above it.
    source = fixture_dir("minimal")
    (source / "defaults" / "common.yml").write_text(
        "site:\n  <<: {region: emea}\n  name: dublin\n", encoding="utf-8"
    )

    result = run_reverie("compile", str(source))

    assert result.returncode != 0
    diagnostics = json.loads(result.stderr)
    assert_diagnostic(diagnostics, "load.value_out_of_domain", kind="merge_key")


def test_unknown_tag_is_rejected(fixture_dir):
    source = fixture_dir("minimal")
    (source / "defaults" / "common.yml").write_text("site: !unknown_tag dublin\n", encoding="utf-8", newline="")

    result = run_reverie("compile", str(source))

    assert result.returncode != 0
    diagnostics = json.loads(result.stderr)
    assert_diagnostic(diagnostics, "load.unknown_tag", tag="!unknown_tag")
