"""Loading and emitting YAML under Reverie's closed value domain.

ADR 0008 closes the value domain to string, integer, float, boolean, null,
list, and map -- exactly JSON's types (the `!vault`/`!secret` tags are a
later ticket's concern). Timestamps, binary, sets, ordered maps, NaN, and
infinity are load errors rather than silently accepted, and anchors,
aliases, and `<<` merge keys are forbidden outright.

Emission is pinned rather than left to a formatter's defaults: UTF-8 with
no BOM, LF, block style, no line wrapping, two-space indent, a `---`
document marker, sorted keys at every depth, and a timestamp-free
generated header.
"""

from __future__ import annotations

import yaml

GENERATED_HEADER = "# Generated by Reverie -- do not edit by hand.\n"

_NAN_INF_VALUES = {
    ".nan",
    ".NaN",
    ".NAN",
    ".inf",
    ".Inf",
    ".INF",
    "-.inf",
    "-.Inf",
    "-.INF",
    "+.inf",
    "+.Inf",
    "+.INF",
}


class ValueDomainError(Exception):
    """A layer file contains something outside Reverie's closed value domain."""

    def __init__(self, kind: str, line: int | None = None):
        self.kind = kind
        self.line = line
        super().__init__(kind)


class UnknownTagError(Exception):
    """A layer file uses a YAML tag Reverie doesn't recognise."""

    def __init__(self, tag: str, line: int | None = None):
        self.tag = tag
        self.line = line
        super().__init__(tag)


_ALLOWED_TAGS = {
    "tag:yaml.org,2002:map",
    "tag:yaml.org,2002:seq",
    "tag:yaml.org,2002:str",
    "tag:yaml.org,2002:int",
    "tag:yaml.org,2002:float",
    "tag:yaml.org,2002:bool",
    "tag:yaml.org,2002:null",
}

_FORBIDDEN_TAG_KINDS = {
    "tag:yaml.org,2002:timestamp": "timestamp",
    "tag:yaml.org,2002:binary": "binary",
    "tag:yaml.org,2002:set": "set",
    "tag:yaml.org,2002:omap": "ordered_map",
    "tag:yaml.org,2002:pairs": "ordered_map",
    "tag:yaml.org,2002:merge": "merge_key",
}


class _ClosedLoader(yaml.SafeLoader):
    """A SafeLoader restricted to Reverie's closed value domain."""

    def compose_node(self, parent, index):
        # Composer.compose_document() clears self.anchors once the whole
        # document is composed, so it can't be inspected afterwards --
        # anchors and aliases are rejected here, at the point each node
        # is composed, instead.
        event = self.peek_event()
        if isinstance(event, yaml.AliasEvent):
            raise ValueDomainError("anchor_or_alias", event.start_mark.line + 1)
        if getattr(event, "anchor", None):
            raise ValueDomainError("anchor_or_alias", event.start_mark.line + 1)
        return super().compose_node(parent, index)


def _construct_float(loader: yaml.SafeLoader, node: yaml.ScalarNode):
    if node.value in _NAN_INF_VALUES:
        raise ValueDomainError("nan_or_infinity", node.start_mark.line + 1)
    return yaml.SafeLoader.construct_yaml_float(loader, node)


_ClosedLoader.add_constructor("tag:yaml.org,2002:float", _construct_float)


def _check_tags(node: yaml.Node) -> None:
    """Walk the composed node tree, rejecting any tag outside the closed domain."""

    if node.tag in _FORBIDDEN_TAG_KINDS:
        raise ValueDomainError(_FORBIDDEN_TAG_KINDS[node.tag], node.start_mark.line + 1)
    if node.tag not in _ALLOWED_TAGS:
        raise UnknownTagError(node.tag, node.start_mark.line + 1)

    if isinstance(node, yaml.MappingNode):
        for key_node, value_node in node.value:
            _check_tags(key_node)
            _check_tags(value_node)
    elif isinstance(node, yaml.SequenceNode):
        for item_node in node.value:
            _check_tags(item_node)


def load_closed_domain(text: str):
    """Parse YAML text, enforcing the closed value domain.

    Raises ValueDomainError, UnknownTagError, or yaml.YAMLError (malformed
    YAML) on violation.
    """

    loader = _ClosedLoader(text)
    try:
        node = loader.get_single_node()
        if node is None:
            return None
        _check_tags(node)
        return loader.construct_document(node)
    finally:
        loader.dispose()


class _PinnedDumper(yaml.SafeDumper):
    """A SafeDumper with Reverie's pinned serialisation mechanics."""


def _represent_dict(dumper: yaml.SafeDumper, data: dict):
    return dumper.represent_mapping(
        "tag:yaml.org,2002:map", sorted(data.items(), key=lambda kv: kv[0])
    )


_PinnedDumper.add_representer(dict, _represent_dict)
_PinnedDumper.ignore_aliases = lambda self, data: True


def dump_pinned(data: dict) -> str:
    """Serialise `data` under Reverie's pinned artifact mechanics.

    Block style, two-space indent, no line wrapping, sorted keys at every
    depth, `---` marker, no trailing document-end marker.
    """

    return yaml.dump(
        data,
        Dumper=_PinnedDumper,
        default_flow_style=False,
        explicit_start=True,
        allow_unicode=True,
        indent=2,
        width=1_000_000,
        sort_keys=True,
    )


def write_generated_file(data: dict) -> bytes:
    """Render `data` with the generated header, returning the exact bytes to write."""

    text = GENERATED_HEADER + dump_pinned(data)
    return text.encode("utf-8")


def has_generated_header(path) -> bool:
    try:
        with open(path, "r", encoding="utf-8", newline="") as handle:
            first_line = handle.readline()
    except (FileNotFoundError, UnicodeDecodeError):
        return False
    return first_line == GENERATED_HEADER
