"""Loading and emitting YAML under Reverie's closed value domain.

ADR 0008 closes the value domain to string, integer, float, boolean, null,
list, and map -- exactly JSON's types, plus `!vault` and `!secret`.
Timestamps, binary, sets, ordered maps, NaN, and
infinity are load errors rather than silently accepted, and anchors,
aliases, and `<<` merge keys are forbidden outright.

A second, permissive loader (`load_permissive`) sits beside the closed one
for `enumerate`'s fact read, which runs before `load` and so must not fail
a compile on anything `load` will report properly a phase later. It knows
the three tags and enforces nothing else.

Emission is pinned rather than left to a formatter's defaults: UTF-8 with
no BOM, LF, block style, no line wrapping, two-space indent, a `---`
document marker, sorted keys at every depth, and a timestamp-free
generated header.
"""

from __future__ import annotations

import re

import yaml

GENERATED_HEADER = "# Generated by Reverie -- do not edit by hand.\n"

_NAN_INF_VALUES = {
    ".nan",
    ".NaN",
    ".NAN",
    ".inf",
    ".Inf",
    ".INF",
    "-.inf",
    "-.Inf",
    "-.INF",
    "+.inf",
    "+.Inf",
    "+.INF",
}


class SourceConditionError(Exception):
    """A source-file violation that maps straight onto a `load.*` condition.

    Every source-level rule this module enforces reports through this one
    exception: the condition names itself, the position it was found at
    rides along, and whatever else that condition declares (`kind`, `tag`)
    arrives as a keyword. One parameterised exception covers them rather
    than a class per condition, and the caller is left with nothing to
    translate -- it supplies the `file`, which is the one field it knows
    and this module doesn't, and forwards the rest.

    A condition the registry declares with no fields at all is raised
    `positioned=False` -- there being no `line` to carry, there is no
    `file` either. Said at the raise site rather than inferred from a
    missing line, so a rule that simply couldn't find its position still
    reports the file it was found in.
    """

    def __init__(
        self,
        condition: str,
        line: int | None = None,
        *,
        positioned: bool = True,
        **fields,
    ):
        self.condition = condition
        self.line = line
        self.positioned = positioned
        self.fields = fields
        super().__init__(condition)

    def declared_fields(self, *, file: str) -> dict:
        """Every field this condition declares, given the file the caller opened.

        `file` and `line` are the position, and a positioned condition
        declares both; the rest is what the raise site named. A condition
        raised unpositioned declares neither, and `file` would be a field
        its registry entry doesn't have.
        """

        if not self.positioned:
            return dict(self.fields)
        return {**self.fields, "file": file, "line": self.line}


def _value_out_of_domain(kind: str, node: yaml.Node) -> SourceConditionError:
    """`load.value_out_of_domain` at `node`, naming the closed-domain rule broken.

    Three rules report it -- ADR 0008's forbidden types, NaN/infinity, and
    a non-scalar `!vault` -- so the slug and the one-based line live here
    rather than once per raise site.
    """

    return SourceConditionError("load.value_out_of_domain", node.start_mark.line + 1, kind=kind)


_FACT_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# The two top-level names the artifact itself occupies (ADR 0004) -- a layer
# that declared either would resolve into a key that collides with, or
# silently shadows, the artifact's own namespacing.
_RESERVED_NAMES = {"reverie", "reverie_meta"}

# CONTEXT.md "Key path": `/` separates segments, so a key containing one
# would be unaddressable by any `merge:` or secrets pattern.
_KEY_PATH_SEPARATOR = "/"


REMOVE_TAG = "!remove"


class Remove:
    """Marker for a `!remove`-tagged value (CONTEXT.md "!remove").

    Never emitted and holds no position in a merged result -- what it was
    tagged onto contributes a *match*, not an element. For map-key removal
    that's the whole story: identity comes from the key, not the value.
    List-element removal needs more: `!remove foo` must still know it was
    "foo" so list-merge can find the general-layer element it matches, so
    `value` carries the tagged node's own constructed content (`None` for
    a bare `!remove`).
    """

    __slots__ = ("value",)

    def __init__(self, value=None):
        self.value = value

    def __repr__(self) -> str:
        return "!remove"

VAULT_TAG = "!vault"


class Vault:
    """Marker for a `!vault`-tagged scalar (CONTEXT.md "!vault").

    Opaque by construction: `value` is the tagged node's raw scalar text,
    carried verbatim through load, validate, and resolve, untouched by
    anything that would inspect, interpolate, or compare it -- ADR 0006.
    """

    __slots__ = ("value",)

    def __init__(self, value: str):
        self.value = value

    def __repr__(self) -> str:
        return f"!vault {self.value!r}"


_ALLOWED_TAGS = {
    "tag:yaml.org,2002:map",
    "tag:yaml.org,2002:seq",
    "tag:yaml.org,2002:str",
    "tag:yaml.org,2002:int",
    "tag:yaml.org,2002:float",
    "tag:yaml.org,2002:bool",
    "tag:yaml.org,2002:null",
}

_FORBIDDEN_TAG_KINDS = {
    "tag:yaml.org,2002:timestamp": "timestamp",
    "tag:yaml.org,2002:binary": "binary",
    "tag:yaml.org,2002:set": "set",
    "tag:yaml.org,2002:omap": "ordered_map",
    "tag:yaml.org,2002:pairs": "ordered_map",
}

# `<<` is a third, shallow, parse-time merge that would bypass the declared
# policy layer entirely (ADR 0008), so it joins anchors and aliases under
# load.forbidden_alias rather than the generic value-domain condition.
_MERGE_TAG = "tag:yaml.org,2002:merge"


class _ClosedLoader(yaml.SafeLoader):
    """A SafeLoader restricted to Reverie's closed value domain."""

    def compose_node(self, parent, index):
        # Composer.compose_document() clears self.anchors once the whole
        # document is composed, so it can't be inspected afterwards --
        # anchors and aliases are rejected here, at the point each node
        # is composed, instead.
        event = self.peek_event()
        if isinstance(event, yaml.AliasEvent) or getattr(event, "anchor", None):
            raise SourceConditionError("load.forbidden_alias", event.start_mark.line + 1)
        return super().compose_node(parent, index)


def _construct_float(loader: yaml.SafeLoader, node: yaml.ScalarNode):
    if node.value in _NAN_INF_VALUES:
        raise _value_out_of_domain("nan_or_infinity", node)
    return yaml.SafeLoader.construct_yaml_float(loader, node)


_ClosedLoader.add_constructor("tag:yaml.org,2002:float", _construct_float)


def _construct_remove(loader: yaml.SafeLoader, node: yaml.Node) -> Remove:
    # The node's own tag is `!remove`, so construct it as whatever it would
    # have resolved to without that tag (a clone with the implicit tag),
    # rather than re-entering this constructor.
    if isinstance(node, yaml.ScalarNode):
        tag = loader.resolve(yaml.ScalarNode, node.value, (True, False))
        clone = yaml.ScalarNode(tag, node.value, node.start_mark, node.end_mark, node.style)
    elif isinstance(node, yaml.MappingNode):
        clone = yaml.MappingNode(
            "tag:yaml.org,2002:map", node.value, node.start_mark, node.end_mark, node.flow_style
        )
    elif isinstance(node, yaml.SequenceNode):
        clone = yaml.SequenceNode(
            "tag:yaml.org,2002:seq", node.value, node.start_mark, node.end_mark, node.flow_style
        )
    else:
        return Remove(None)
    return Remove(loader.construct_object(clone, deep=True))


_ClosedLoader.add_constructor(REMOVE_TAG, _construct_remove)


def _construct_vault(loader: yaml.SafeLoader, node: yaml.Node) -> Vault:
    # `_check_tags` has already rejected a non-scalar `!vault` node before
    # construction reaches here, so `node.value` is always the raw text.
    return Vault(node.value)


_ClosedLoader.add_constructor(VAULT_TAG, _construct_vault)


SECRET_TAG = "!secret"


class Secret:
    """Marker for a `!secret <address>`-tagged scalar (CONTEXT.md "!secret").

    A structured reference, not material: `address` is the tagged node's
    raw scalar text, carried verbatim through load, validate, and resolve,
    translated to the declared backend's native call only at emit. Unlike
    `Vault`, address equality is meaningful -- `!secret` values compare by
    `address` so they participate fully in `unique`/tuple merge strategies
    (ADR 0006).
    """

    __slots__ = ("address",)

    def __init__(self, address: str):
        self.address = address

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Secret) and self.address == other.address

    def __hash__(self) -> int:
        return hash(("Secret", self.address))

    def __repr__(self) -> str:
        return f"!secret {self.address!r}"


def _construct_secret(loader: yaml.SafeLoader, node: yaml.Node) -> Secret:
    # `_check_tags` has already rejected a non-scalar or empty `!secret`
    # node before construction reaches here.
    return Secret(node.value)


_ClosedLoader.add_constructor(SECRET_TAG, _construct_secret)


class TaggedFact:
    """A host-file value `enumerate` saw carrying one of Reverie's own tags.

    The fact parse never interprets a tagged value -- `load` is the one
    authority on whether the tag is legal where it sits, and on what it
    means. All this marker records is *that* the value is tagged, which is
    enough for enumerate: none of the three tags yields something a chain
    address, a group name, or an `ansible_host` could be built from.
    """

    __slots__ = ("tag",)

    def __init__(self, tag: str):
        self.tag = tag

    def __repr__(self) -> str:
        return self.tag


class _FactLoader(yaml.SafeLoader):
    """A SafeLoader that tolerates Reverie's tags instead of raising on them.

    Deliberately not `_ClosedLoader`: this loader enforces none of the
    closed-domain rules, because the phase it serves (enumerate, before
    load has run) must not fail a compile on a value load.py will reject
    a phase later with a proper, positioned diagnostic.
    """


def _construct_tagged_fact(loader: yaml.SafeLoader, node: yaml.Node) -> TaggedFact:
    # The tagged node's content is never constructed -- not even for a
    # scalar. Nothing downstream of the fact parse can use it, and leaving
    # it unread keeps this loader free of any opinion about what is legal
    # under a tag.
    return TaggedFact(node.tag)


for _tag in (REMOVE_TAG, VAULT_TAG, SECRET_TAG):
    _FactLoader.add_constructor(_tag, _construct_tagged_fact)


def load_permissive(text: str):
    """Parse YAML text knowing Reverie's tags but enforcing nothing else.

    For `enumerate`'s fact read only. Raises `yaml.YAMLError` on malformed
    YAML; every tagged value constructs to a `TaggedFact` rather than
    raising, so one tag costs only itself and never the file's other keys.
    """

    return yaml.load(text, Loader=_FactLoader)


def _check_resolved_tag(tag: str, node: yaml.Node) -> None:
    if tag == _MERGE_TAG:
        raise SourceConditionError("load.forbidden_alias", node.start_mark.line + 1)
    if tag in _FORBIDDEN_TAG_KINDS:
        raise _value_out_of_domain(_FORBIDDEN_TAG_KINDS[tag], node)
    if tag not in _ALLOWED_TAGS:
        raise SourceConditionError("load.unknown_tag", node.start_mark.line + 1, tag=tag)


def _deferred_template_balanced(text: str) -> bool:
    """Whether every `{{` in `text` closes with a matching `}}`.

    Deferred Jinja is inert literal text -- never parsed, only
    balance-checked (CONTEXT.md "Deferred Jinja") -- so this is the whole
    check: no nesting, no stray closer, nothing left open.
    """

    open_span = False
    index = 0
    while index < len(text):
        if text.startswith("{{", index):
            if open_span:
                return False
            open_span = True
            index += 2
        elif text.startswith("}}", index):
            if not open_span:
                return False
            open_span = False
            index += 2
        else:
            index += 1
    return not open_span


def _check_mapping_keys(loader: yaml.SafeLoader, node: yaml.MappingNode, top_level_of_host: bool) -> None:
    """Every key in one mapping: a string, separator-free, and unique.

    A host file's own top-level keys are additionally held to the chain
    template's identifier grammar -- they're the facts `{{ host.<name> }}`
    substitutes, so a name that grammar can't address is dead weight the
    chain could never reach.
    """

    seen: set[str] = set()
    for key_node, _value_node in node.value:
        line = key_node.start_mark.line + 1
        if key_node.tag == _MERGE_TAG:
            raise SourceConditionError("load.forbidden_alias", line)
        if not isinstance(key_node, yaml.ScalarNode) or key_node.tag != "tag:yaml.org,2002:str":
            raise SourceConditionError("load.non_string_key", line)

        key = key_node.value
        if _KEY_PATH_SEPARATOR in key:
            raise SourceConditionError("load.key_contains_separator", line)
        if key in seen:
            raise SourceConditionError("load.duplicate_key", line)
        seen.add(key)

        if top_level_of_host and not _FACT_NAME.fullmatch(key):
            raise SourceConditionError("load.illegal_fact_name", line)


def _check_tags(loader: yaml.SafeLoader, node: yaml.Node, *, root_of: str | None = None) -> None:
    """Walk the composed node tree, rejecting every source-level violation.

    `root_of` is `"host"` or `"layer"` on the document's own root node and
    None below it -- only a root mapping's keys are top-level names, so
    only there do the reserved-name and fact-name rules apply.
    """

    if node.tag == REMOVE_TAG:
        # The tag itself is exempt from the allowed-tags check, but its
        # underlying content is still constructed (for list-element
        # matching) and so still has to live in the closed domain -- a
        # scalar's *implicit* tag (e.g. a bare timestamp) included, since
        # nothing else resolves or checks it once `!remove` intercepts
        # the node's own tag.
        if isinstance(node, yaml.MappingNode):
            _check_mapping_keys(loader, node, top_level_of_host=False)
            for _key_node, value_node in node.value:
                _check_tags(loader, value_node)
        elif isinstance(node, yaml.SequenceNode):
            for item_node in node.value:
                _check_tags(loader, item_node)
        elif isinstance(node, yaml.ScalarNode):
            resolved = loader.resolve(yaml.ScalarNode, node.value, (True, False))
            _check_resolved_tag(resolved, node)
        return

    if node.tag == VAULT_TAG:
        # Opaque by construction: a `!vault` scalar's content is never
        # inspected, so nothing about it needs checking beyond "it is a
        # scalar" -- tagging a map or sequence (including the whole
        # document) is rejected instead of silently accepted, since a
        # merge engine needs to see the values it merges (ADR 0006).
        if not isinstance(node, yaml.ScalarNode):
            raise _value_out_of_domain("vault_not_scalar", node)
        return

    if node.tag == SECRET_TAG:
        # A structured address, not material -- still only a scalar makes
        # sense as "an address", and an empty one is unusable (the two
        # acceptance criteria this tag's ticket names).
        if not isinstance(node, yaml.ScalarNode) or not node.value.strip():
            # The registry declares `load.empty_secret_address` with no
            # fields at all, so the line this node sits at is deliberately
            # not carried. Giving it one is a registry change, argued on
            # its own.
            raise SourceConditionError("load.empty_secret_address", positioned=False)
        return

    _check_resolved_tag(node.tag, node)

    if isinstance(node, yaml.ScalarNode) and node.tag == "tag:yaml.org,2002:str":
        if not _deferred_template_balanced(node.value):
            raise SourceConditionError("load.malformed_deferred_template", node.start_mark.line + 1)

    if isinstance(node, yaml.MappingNode):
        _check_mapping_keys(loader, node, top_level_of_host=root_of == "host")
        if root_of is not None:
            for key_node, _value_node in node.value:
                if key_node.value in _RESERVED_NAMES:
                    raise SourceConditionError(
                        "load.reserved_name_key", key_node.start_mark.line + 1
                    )
        for _key_node, value_node in node.value:
            _check_tags(loader, value_node)
    elif isinstance(node, yaml.SequenceNode):
        for item_node in node.value:
            _check_tags(loader, item_node)


def load_closed_domain(text: str, *, host_file: bool = False):
    """Parse YAML text, enforcing every source-level rule.

    Raises `SourceConditionError` naming the condition violated, or
    `yaml.YAMLError` -- PyYAML's own, for malformed YAML.
    """

    loader = _ClosedLoader(text)
    try:
        # check_node() drops the stream-start event and reports whether a
        # document follows -- get_node() alone would hand compose_document
        # an unconsumed stream-start.
        if not loader.check_node():
            return None
        node = loader.get_node()
        if loader.check_node():
            # Peeked, not composed: the second document's own content may
            # be anything, and "there is a second document at all" is the
            # whole finding.
            raise SourceConditionError(
                "load.multiple_documents", loader.peek_event().start_mark.line + 1
            )
        _check_tags(loader, node, root_of="host" if host_file else "layer")
        return loader.construct_document(node)
    finally:
        loader.dispose()


class _PinnedDumper(yaml.SafeDumper):
    """A SafeDumper with Reverie's pinned serialisation mechanics."""


def _represent_dict(dumper: yaml.SafeDumper, data: dict):
    return dumper.represent_mapping(
        "tag:yaml.org,2002:map", sorted(data.items(), key=lambda kv: kv[0])
    )


def _represent_vault(dumper: yaml.SafeDumper, data: Vault):
    return dumper.represent_scalar(VAULT_TAG, data.value)


def _represent_secret(dumper: yaml.SafeDumper, data: Secret):
    return dumper.represent_scalar(SECRET_TAG, data.address)


_PinnedDumper.add_representer(dict, _represent_dict)
_PinnedDumper.add_representer(Vault, _represent_vault)
_PinnedDumper.add_representer(Secret, _represent_secret)
_PinnedDumper.ignore_aliases = lambda self, data: True


def dump_pinned(data: dict) -> str:
    """Serialise `data` under Reverie's pinned artifact mechanics.

    Block style, two-space indent, no line wrapping, sorted keys at every
    depth, `---` marker, no trailing document-end marker.
    """

    return yaml.dump(
        data,
        Dumper=_PinnedDumper,
        default_flow_style=False,
        explicit_start=True,
        allow_unicode=True,
        indent=2,
        width=1_000_000,
        sort_keys=True,
    )


def dump_flow_scalar(value: object) -> str:
    """One scalar as YAML writes it *inside a flow collection*.

    The rendering an RSOP address's element selector uses (CONTEXT.md
    "RSOP address"). A selector is visually a flow collection --
    `[name=admins,ttl=30]` -- and YAML's own flow rules already quote
    exactly what would otherwise be ambiguous there: a value containing
    `,`, `[` or `]`, the empty string, and anything that would read back
    as another type (`true`, `7`). So the selector needs no escape scheme
    of its own, and `!vault`/`!secret` keep their tags.

    One addition YAML has no reason to make: `/` separates key-path
    segments, so a value containing one is quoted too. Otherwise a
    `C:\\Shares` tuple key would put a spurious segment boundary inside
    an address. A tag is not part of the scalar it marks, so the quoting
    goes around the content and leaves the tag outside it.
    """

    rendered = yaml.dump(
        [value],
        Dumper=_PinnedDumper,
        default_flow_style=True,
        allow_unicode=True,
        width=1_000_000,
    ).strip()
    rendered = rendered.removeprefix("[").removesuffix("]")

    tag = ""
    if rendered.startswith("!"):
        tag, _, rendered = rendered.partition(" ")
        tag += " "

    if "/" in rendered and not rendered.startswith("'"):
        rendered = "'" + rendered.replace("'", "''") + "'"
    return tag + rendered


def write_generated_file(data: dict) -> bytes:
    """Render `data` with the generated header, returning the exact bytes to write."""

    text = GENERATED_HEADER + dump_pinned(data)
    return text.encode("utf-8")


def has_generated_header(path) -> bool:
    try:
        with open(path, "r", encoding="utf-8", newline="") as handle:
            first_line = handle.readline()
    except (FileNotFoundError, UnicodeDecodeError):
        return False
    return first_line == GENERATED_HEADER
