"""Regenerates docs/spec-registry.md from spec/*.yml.

The registry (spec/error-conditions.yml and its siblings) is the single
source of truth; this script is the documented generation step issue #31
requires so prose tables are never hand-maintained separately.

Run after editing spec/*.yml:

    python scripts/generate_spec_docs.py

tests/test_spec_registry.py fails the build if the checked-in doc drifts
from what this script would produce.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from reverie import spec_registry  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "spec-registry.md"


def _error_condition_table(entries: dict[str, dict]) -> list[str]:
    lines = ["| id | fields | implemented |", "| --- | --- | --- |"]
    for id in sorted(entries):
        entry = entries[id]
        fields = ", ".join(entry["fields"]) or "--"
        implemented = "yes" if entry.get("implemented") else "no"
        lines.append(f"| `{id}` | {fields} | {implemented} |")
    return lines


def render() -> str:
    lines = [
        "<!-- Generated by scripts/generate_spec_docs.py from spec/*.yml. Do not edit by hand. -->",
        "",
        "# Reverie spec registry",
        "",
        "The closed vocabularies the compiler and its conformance fixtures cite by name.",
        "",
    ]

    for phase in spec_registry.PHASES:
        entries = {
            id: entry
            for id, entry in spec_registry.error_conditions().items()
            if entry["phase"] == phase
        }
        lines.append(f"## {phase}")
        lines.append("")
        if entries:
            lines.extend(_error_condition_table(entries))
        else:
            lines.append("_No error conditions._")
        lines.append("")

    lines.append("## Warnings")
    lines.append("")
    lines.extend(_error_condition_table(spec_registry.warnings()))
    lines.append("")

    lines.append("## Merge strategies")
    lines.append("")
    lines.append("| id | shape | description |")
    lines.append("| --- | --- | --- |")
    for id, entry in spec_registry.strategies().items():
        lines.append(f"| `{id}` | {entry['shape']} | {entry['description']} |")
    lines.append("")

    lines.append("## Tags")
    lines.append("")
    lines.append("| id | lifecycle | description |")
    lines.append("| --- | --- | --- |")
    for id, entry in spec_registry.tags().items():
        lines.append(f"| `{id}` | {entry['lifecycle']} | {entry['description']} |")
    lines.append("")

    lines.append("## Value shapes")
    lines.append("")
    for shape in spec_registry.value_shapes():
        lines.append(f"- `{shape}`")
    lines.append("")

    lines.append("## RSOP contributor outcomes")
    lines.append("")
    for outcome in spec_registry.contributor_outcomes():
        lines.append(f"- `{outcome}`")
    lines.append("")

    rsop_vocab = spec_registry.rsop_vocabulary()
    lines.append("## RSOP annotations")
    lines.append("")
    for annotation in rsop_vocab["annotations"]:
        lines.append(f"- `{annotation}`")
    lines.append("")

    lines.append("## RSOP redaction reasons")
    lines.append("")
    for reason in rsop_vocab["redaction_reasons"]:
        lines.append(f"- `{reason}`")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
